### ISSUE TITLE
The demo does not work

### ISSUE THREAD

**Issue by mattes3** [marklundin/glsl-sdf-primitives#5]
The README.md file links to a [demo on glslb.in](http://glslb.in/s/464383f8). That demo does not run because the server returns an error 500 and says:

```
Missing package version (glsl-square-frame)
Error: Missing package version (glsl-square-frame)
    at getFile (/app/node_modules/npmdl/index.js:24:28)
    at gotVersion (/app/node_modules/glslify-resolve-remote/index.js:76:7)
    at Request._callback (/app/node_modules/glslify-resolve-remote/index.js:69:9)
    at Request.self.callback (/app/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:962:12)
```

**Comment by DEF7** [comment]
This issue still exists, except now it's a Heroku thing rather than a 500 HTTP error.

![image](https://user-images.githubusercontent.com/11559157/234785468-fb17d9cc-4bdc-4230-a81b-8c0d5918592f.png)

I'd love to see the demo!
